
export const robots =[
    {
        id:1,
        name:'Braddy',
        username:'Brad',
        email:'brad@gamil.com'
    },
    {
        id:2,
        name:'Sally',
        username:'Sal',
        email:'brad@git.com'
    },
    {
        id:3,
        name:'Bobby',
        username:'Bob',
        email:'bobsal@gutter.com'
    },
    {
        id:4,
        name:'Billy',
        username:'Bil',
        email:'bil@git.com'
    },
    {
        id:5,
        name:'Samuel',
        username:'Sam',
        email:'sam@hit.com'
    },
    {
        id:6,
        name:'Rachel',
        username:'Rach',
        email:'rach@hit.com'
    },
    {
        id:7,
        name:'Sobby',
        username:'Sob',
        email:'sob@git.com'
    },
    {
        id:8,
        name:'Border',
        username:'Der',
        email:'der@hit.com'
    },
    {
        id:9,
        name:'Biguel',
        username:'Big',
        email:'big@hit.com'
    },
    {
        id:10,
        name:'Rosssell',
        username:'Ross',
        email:'ross@hit.com'
    }
]